---
title: Jalpc
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Jack's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl: "/Jalpc"
url: https://jarrekk.github.io/Jalpc
img_path: "/Jalpc/static/assets/img/blog"
author:
  name: GitHub
  first_name: Hub
  last_name: Git
  avatar: "/static/assets/img/landing/avatar.jpg"
  github_username: jarrekk
  linkedin_id: jarrekk
  facebook_username: jiakunnj
  twitter_username: jiakun614
  email: me@jarrekk.com
  cv: http://cv.jarrekk.com
  skill_icon1:
  - name: icon-apache
  - name: fa-linux
  skill_icon2:
  - name: fa-linux
  - name: icon-apache
  desc: Introduce myself will be here.
disqus:
  name: jalpc
ga:
  id: UA-93473370-3
go: 
gio: 
donation: true
index_carousel: true
blog_carousel: true
sass:
  style: compressed
encoding: utf-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
